spring.application.name=monitoring-demo
# M? c?ng 8080 cho ?ng d?ng
server.port=8080

# C?U HÌNH QUAN TR?NG: Cho phép Prometheus ??c d? li?u
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true